language: objective-c
osx_image: xcode8
xcode_project: Medication.xcodeproj
xcode_scheme: Medication
xcode_sdk: iphonesimulator10.0
before_install:
- sudo security delete-certificate -c "Apple Worldwide Developer Relations Certification Authority" /Library/Keychains/System.keychain
- sudo security delete-certificate -c "Apple Worldwide Developer Relations Certification Authority" /Library/Keychains/login.keychain
- sudo curl -O -L http://developer.apple.com/certificationauthority/AppleWWDRCA.cer
- sudo security import AppleWWDRCA.cer  -k ~/Library/Keychains/login.keychain -A
